### ISSUE TITLE
CM buildImage step failing due to missing dependency

### ISSUE THREAD

**Issue by andrewmkhoury** [adobe/asset-share-commons#607]
**Describe the bug**
Cloud Manager builds for customers including assetshare.all-2.0.2 as a sub-package have recently started failing.

**Environment**
* AEM Version: Latest Cloud Manager version
* Asset Share Commons Version: 2.0.2
* Deploys for all environments

**To Reproduce**
1. Deploy assetshare.all-2.0.2.zip as a subpackage with a cloud manager deploy
3. buildImage step fails with this error
```
[ERROR] Error while assembling launcher: Package has unresolved dependencies: adobe/cq60:core.wcm.components.content:2.14.0
shaded.org.apache.jackrabbit.vault.packaging.DependencyException: Package has unresolved dependencies: adobe/cq60:core.wcm.components.content:2.14.0
	at shaded.org.apache.jackrabbit.vault.packaging.registry.impl.ExecutionPlanBuilderImpl.resolveInstall(ExecutionPlanBuilderImpl.java:257)
	at shaded.org.apache.jackrabbit.vault.packaging.registry.impl.ExecutionPlanBuilderImpl.validate(ExecutionPlanBuilderImpl.java:239)
	at org.apache.sling.feature.extension.content.ContentHandler.buildExecutionPlan(ContentHandler.java:87)
	at org.apache.sling.feature.extension.content.ContentHandler.handle(ContentHandler.java:128)
	at org.apache.sling.feature.launcher.impl.FeatureProcessor.prepareLauncher(FeatureProcessor.java:212)
	at org.apache.sling.feature.launcher.impl.Bootstrap.run(Bootstrap.java:160)
	at org.apache.sling.feature.launcher.impl.Main.main(Main.java:200)
Exception in thread "main" java.lang.IllegalStateException: The instance is not running
	at com.adobe.granite.composite.init.LogTail.checkInstanceIsAlive(LogTail.java:229)
	at com.adobe.granite.composite.init.LogTail.waitUntilInstanceIsInitialized(LogTail.java:88)
	at com.adobe.granite.composite.init.Main.main(Main.java:67)
```

**Expected behavior**
The buildImage step needs to pass.

**Comment by davidjgonzalez** [comment]
Will be fixed by #608
