### ISSUE TITLE
DownloadsImpls logs warning on AEM 6.5.x

### ISSUE THREAD

**Issue by kwin** [adobe/asset-share-commons#749]
**Describe the bug**
While installing the latest ACS AEM Commons on AEM 6.5.13 the following exception can be seen
```
14.06.2022 10:18:21.184 *WARN* [OsgiInstallerImpl] org.apache.sling.models.impl.AdapterImplementations Unable to reflect on com.adobe.aem.commons.assetshare.components.actions.downloads.impl.DownloadsImpl
java.lang.NoClassDefFoundError: com/adobe/cq/dam/download/api/DownloadException
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructors(Class.java:1943)
	at org.apache.sling.models.impl.model.ModelClass.getConstructors(ModelClass.java:67)
	at org.apache.sling.models.impl.model.ModelClass.updateProcessorFactories(ModelClass.java:57)
	at org.apache.sling.models.impl.model.ModelClass.<init>(ModelClass.java:49)
	at org.apache.sling.models.impl.AdapterImplementations.addAll(AdapterImplementations.java:124)
	at org.apache.sling.models.impl.ModelPackageBundleListener.analyzeClass(ModelPackageBundleListener.java:158)
	at org.apache.sling.models.impl.ModelPackageBundleListener.addingBundle(ModelPackageBundleListener.java:136)
	at org.apache.sling.models.impl.ModelPackageBundleListener.addingBundle(ModelPackageBundleListener.java:53)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:475)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:420)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450)
	at org.apache.felix.framework.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:915)
	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:834)
	at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:516)
	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4817)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2336)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
	at org.apache.sling.installer.core.impl.tasks.BundleStartTask.execute(BundleStartTask.java:97)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.doExecuteTasks(OsgiInstallerImpl.java:914)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.executeTasks(OsgiInstallerImpl.java:749)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.run(OsgiInstallerImpl.java:298)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: com.adobe.cq.dam.download.api.DownloadException not found by com.adobe.aem.commons.assetshare.core [620]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1597)
	at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1982)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 27 common frames omitted
```
**Environment**
* AEM Version: 6.5.13
* Asset Share Commons Version: 2.2.2
* Author, Publish or both: both

**Analysis**

Although this model is supposed to only become active in case the DownloadService is available (which is only the case on AEMCS) it still throws an exception due to the use of reflection in https://github.com/apache/sling-org-apache-sling-models-impl/blob/e658cb305c3eec4045632835057f2e81cabfb0ab/src/main/java/org/apache/sling/models/impl/model/ModelClass.java#L67

**Comment by davidjgonzalez** [comment]
Still good to fix - more understanding the urgency :)
