### ISSUE TITLE
[HTL] Core Components placeholder template "randomly" evaluating to Null.

### ISSUE THREAD

**Issue by hayatkha** [adobe/asset-share-commons#916]
Can someone help me understand why the following is happening (or how to debug) on a AEM CS Publish?
 
I have an HTL script [1] that does a data-sly-call to the Core Components v1 placeholder template.

`<sly data-sly-call="${placeholderTemplate.placeholder @ isEmpty=!ready}"></sly>` [1]

Intermittently this will throw an exception when processing the HTL. 
 
```
Caused by: java.lang.RuntimeException: data-sly-call: expression evaluates to null.
  at org.apache.sling.scripting.sightly.render.RenderUnit.callUnit(RenderUnit.java:75) [org.apache.sling.scripting.sightly.runtime:1.2.6.140]
  at apps.asset__002d__share__002d__commons.components.details.metadata.metadata__002e__html.render(metadata__002e__html.java:171) 
[customer-precompiled-scripts:1.0.0.SNAPSHOT]
  at org.apache.sling.scripting.sightly.render.RenderUnit.render(RenderUnit.java:53) [org.apache.sling.scripting.sightly.runtime:1.2.6.140]
  at org.apache.sling.scripting.sightly.impl.engine.SightlyCompiledScript.eval(SightlyCompiledScript.java:61) [org.apache.sling.scripting.sightly:1.4.20.140]
  at org.apache.sling.scripting.sightly.impl.engine.SightlyScriptEngine.eval(SightlyScriptEngine.java:87) [org.apache.sling.scripting.sightly:1.4.20.140]
  ... 636 common frames omitted
```
 
Looking at the compiled servlet code for this HTL script, we see:
 
```
Object var_templatevar18 = renderContext.getObjectModel().resolveProperty(_global_placeholdertemplate, "placeholder");
    {
        boolean var_templateoptions19_field$_isempty = (!renderContext.getObjectModel().toBoolean(_global_ready));
        {
            java.util.Map var_templateoptions19 = obj().with("isEmpty", var_templateoptions19_field$_isempty);
Line 171 ->            callUnit(out, renderContext, var_templatevar18, var_templateoptions19);
        }
    }
```
 
And looking in RenderUnit.callUnit(..) the exception is thrown when templatevar18 is null.
 
So it looks like, the placeholder template is sometimes null when this HTL is executed, but on a refresh, it might now be. Core Components are installed and that placeholder template exists in the JCR, so what could possibly be causing this behavior? 
 
So far this ONLY happens for this component, and there are many other components on the page/site that also use this placeholder.

ASC version : 2.2.2
Cloud Version :  2023.3.11382.20230315T073850Z

**Comment by davidjgonzalez** [comment]
This was fixed, this was a byproduct of using `.test` instead of `.set` (since this project was created before `.set` was widely supported)
